/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

/**
 *
 * @author caarl
 */
public class frmTicketTrasladoProfes extends javax.swing.JFrame {

    /**
     * Creates new form frmTicketTrasladoProfes
     */
    public frmTicketTrasladoProfes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtCantidadPeople = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtPlantel = new javax.swing.JPasswordField();
        bntAceptarYGenerarPDF = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JButton();
        txtAcompaniante4 = new javax.swing.JPasswordField();
        txtFecha = new javax.swing.JPasswordField();
        btnModificar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtPlantel1 = new javax.swing.JPasswordField();
        jLabel10 = new javax.swing.JLabel();
        txtResponsableID1 = new javax.swing.JPasswordField();
        txtAcompaniante1 = new javax.swing.JPasswordField();
        txtAcompaniante2 = new javax.swing.JPasswordField();
        txtAcompaniante3 = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(65, 164, 205));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Sitka Text", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Datos del viaje:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 160, -1, -1));

        jLabel2.setFont(new java.awt.Font("Sitka Text", 0, 18)); // NOI18N
        jLabel2.setText("Cantidad de personas:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 210, 30));

        txtCantidadPeople.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCantidadPeopleActionPerformed(evt);
            }
        });
        jPanel1.add(txtCantidadPeople, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 210, 30));

        jLabel3.setFont(new java.awt.Font("Sitka Text", 0, 18)); // NOI18N
        jLabel3.setText("Fecha del prestamo:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 340, -1, -1));

        txtPlantel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPlantelActionPerformed(evt);
            }
        });
        jPanel1.add(txtPlantel, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 290, 210, 30));

        bntAceptarYGenerarPDF.setFont(new java.awt.Font("Sitka Text", 0, 18)); // NOI18N
        bntAceptarYGenerarPDF.setText("Aceptar");
        bntAceptarYGenerarPDF.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        bntAceptarYGenerarPDF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntAceptarYGenerarPDFActionPerformed(evt);
            }
        });
        jPanel1.add(bntAceptarYGenerarPDF, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 490, 150, 30));

        jLabel5.setText("Prestamo Profes");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, -1));

        jLabel7.setFont(new java.awt.Font("Sitka Text", 0, 18)); // NOI18N
        jLabel7.setText("Plantel destino:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 270, -1, -1));

        jLabel8.setFont(new java.awt.Font("Sitka Text", 0, 18)); // NOI18N
        jLabel8.setText("Acompañantes:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, -1, -1));

        btnCancelar.setFont(new java.awt.Font("Sitka Text", 0, 18)); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        jPanel1.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 490, 150, 30));

        txtAcompaniante4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAcompaniante4ActionPerformed(evt);
            }
        });
        jPanel1.add(txtAcompaniante4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, 210, 30));

        txtFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFechaActionPerformed(evt);
            }
        });
        jPanel1.add(txtFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 370, 210, 30));

        btnModificar.setFont(new java.awt.Font("Sitka Text", 0, 18)); // NOI18N
        btnModificar.setText("Modificar");
        btnModificar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        jPanel1.add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 490, 150, 30));

        jLabel4.setFont(new java.awt.Font("Sitka Text", 0, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Resumen");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        jLabel6.setFont(new java.awt.Font("Sitka Text", 0, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Asistentes:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));

        jLabel9.setFont(new java.awt.Font("Sitka Text", 0, 18)); // NOI18N
        jLabel9.setText("Plantel origen:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 200, -1, -1));

        txtPlantel1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPlantel1ActionPerformed(evt);
            }
        });
        jPanel1.add(txtPlantel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 220, 210, 30));

        jLabel10.setFont(new java.awt.Font("Sitka Text", 0, 18)); // NOI18N
        jLabel10.setText("ID del responsable:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, -1, -1));

        txtResponsableID1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtResponsableID1ActionPerformed(evt);
            }
        });
        jPanel1.add(txtResponsableID1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 210, 30));

        txtAcompaniante1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAcompaniante1ActionPerformed(evt);
            }
        });
        jPanel1.add(txtAcompaniante1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 210, 30));

        txtAcompaniante2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAcompaniante2ActionPerformed(evt);
            }
        });
        jPanel1.add(txtAcompaniante2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, 210, 30));

        txtAcompaniante3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAcompaniante3ActionPerformed(evt);
            }
        });
        jPanel1.add(txtAcompaniante3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, 210, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 670, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 550, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bntAceptarYGenerarPDFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntAceptarYGenerarPDFActionPerformed
        
      
    }//GEN-LAST:event_bntAceptarYGenerarPDFActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void txtCantidadPeopleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCantidadPeopleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCantidadPeopleActionPerformed

    private void txtAcompaniante4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAcompaniante4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAcompaniante4ActionPerformed

    private void txtFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFechaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFechaActionPerformed

    private void txtPlantelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPlantelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPlantelActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnModificarActionPerformed

    private void txtPlantel1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPlantel1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPlantel1ActionPerformed

    private void txtResponsableID1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtResponsableID1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtResponsableID1ActionPerformed

    private void txtAcompaniante1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAcompaniante1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAcompaniante1ActionPerformed

    private void txtAcompaniante2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAcompaniante2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAcompaniante2ActionPerformed

    private void txtAcompaniante3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAcompaniante3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAcompaniante3ActionPerformed

    /**
     * @param args the command line arguments
     */
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntAceptarYGenerarPDF;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField txtAcompaniante1;
    private javax.swing.JPasswordField txtAcompaniante2;
    private javax.swing.JPasswordField txtAcompaniante3;
    private javax.swing.JPasswordField txtAcompaniante4;
    private javax.swing.JTextField txtCantidadPeople;
    private javax.swing.JPasswordField txtFecha;
    private javax.swing.JPasswordField txtPlantel;
    private javax.swing.JPasswordField txtPlantel1;
    private javax.swing.JPasswordField txtResponsableID1;
    // End of variables declaration//GEN-END:variables
}
