/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import DTO.PrestamoMaestrosDTO;
import excepcion.FachadaExceptionPDF;
import fachada.PrestamoMaestrosFCDPDF;
import guardar.Guardar;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author caarl
 */
public class frmTicketTrasladoProfes extends javax.swing.JFrame {

    /**
     * Creates new form frmTicketTrasladoProfes
     */
Guardar guardar = new Guardar();
    private final PrestamoMaestrosDTO prestamo = guardar.getPrestamoProfes();
    
    public frmTicketTrasladoProfes() {

        initComponents();
        llenarCampos();
        
    }
    
    private void llenarCampos() {
    
        txtCorreoResponsable.setEditable(false);
        txtAcompaniante1.setEditable(false);
        txtAcompaniante2.setEditable(false);
        txtAcompaniante3.setEditable(false);
        txtAcompaniante4.setEditable(false);
        txtVehiculo.setEditable(false);
        txtPlantelDestino.setEditable(false);
        txtPlantelOrigen.setEditable(false);
        txtCantPersonas.setEditable(false);
        txtFecha.setEditable(false);
        txtMotivo.setEditable(false);

        if (prestamo != null) {
        txtFecha.setText(prestamo.getFechaPrestamo().toString());
        txtCantPersonas.setText(String.valueOf(prestamo.getCantidadPersonas()));
        txtMotivo.setText(prestamo.getMotivo());
        txtPlantelOrigen.setText(prestamo.getPlantelOrigen());
        txtPlantelDestino.setText(prestamo.getPlantelDestino());
        txtVehiculo.setText(prestamo.getVehiculo());
        txtCorreoResponsable.setText(prestamo.getCorreoResponsable());

        // Llenar los campos de acompañantes
        List<String> acompaniantes = prestamo.getAcompaniantes();
        JTextField[] acompanianteFields = {txtAcompaniante1, txtAcompaniante2, txtAcompaniante3, txtAcompaniante4,
                                               };
        
        for (int i = 0; i < acompaniantes.size() && i < acompanianteFields.length; i++) {
            acompanianteFields[i].setText(acompaniantes.get(i));
        }
    } else {
        JOptionPane.showMessageDialog(this, "No se encontró información del préstamo", "Error", JOptionPane.ERROR_MESSAGE);
    }
}
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        bntAceptarYGenerarPDF = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        txtCantPersonas = new javax.swing.JTextField();
        txtCorreoResponsable = new javax.swing.JTextField();
        txtPlantelOrigen = new javax.swing.JTextField();
        txtPlantelDestino = new javax.swing.JTextField();
        txtVehiculo = new javax.swing.JTextField();
        txtFecha = new javax.swing.JTextField();
        txtMotivo = new javax.swing.JTextField();
        txtAcompaniante1 = new javax.swing.JTextField();
        txtAcompaniante3 = new javax.swing.JTextField();
        txtAcompaniante4 = new javax.swing.JTextField();
        txtAcompaniante2 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(65, 164, 205));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Sitka Text", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Datos del viaje:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 80, -1, -1));

        jLabel2.setFont(new java.awt.Font("Sitka Text", 0, 18)); // NOI18N
        jLabel2.setText("Cantidad de personas:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 210, 30));

        jLabel3.setFont(new java.awt.Font("Sitka Text", 0, 18)); // NOI18N
        jLabel3.setText("Vehiculo:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 250, -1, -1));

        jLabel5.setText("Prestamo Profes");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, -1));

        jLabel7.setFont(new java.awt.Font("Sitka Text", 0, 18)); // NOI18N
        jLabel7.setText("Plantel destino:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 190, -1, -1));

        jLabel8.setFont(new java.awt.Font("Sitka Text", 0, 18)); // NOI18N
        jLabel8.setText("Acompañantes:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, -1, -1));

        jLabel4.setFont(new java.awt.Font("Sitka Text", 0, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Resumen");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        jLabel6.setFont(new java.awt.Font("Sitka Text", 0, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Asistentes:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));

        jLabel9.setFont(new java.awt.Font("Sitka Text", 0, 18)); // NOI18N
        jLabel9.setText("Plantel origen:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 120, -1, -1));

        jLabel10.setFont(new java.awt.Font("Sitka Text", 0, 18)); // NOI18N
        jLabel10.setText("Correo del responsable:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, -1, -1));

        jPanel2.setBackground(new java.awt.Color(65, 164, 205));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("Sitka Text", 0, 36)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Datos del viaje:");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 80, -1, -1));

        jLabel13.setFont(new java.awt.Font("Sitka Text", 0, 18)); // NOI18N
        jLabel13.setText("Cantidad de personas:");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 210, 30));

        jLabel14.setFont(new java.awt.Font("Sitka Text", 0, 18)); // NOI18N
        jLabel14.setText("Vehiculo:");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 250, -1, -1));

        jLabel15.setText("Prestamo Profes");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, -1));

        jLabel16.setFont(new java.awt.Font("Sitka Text", 0, 18)); // NOI18N
        jLabel16.setText("Plantel destino:");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 190, -1, -1));

        jLabel17.setFont(new java.awt.Font("Sitka Text", 0, 18)); // NOI18N
        jLabel17.setText("Acompañantes:");
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, -1, -1));

        jLabel18.setFont(new java.awt.Font("Sitka Text", 0, 36)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Resumen");
        jPanel2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        jLabel19.setFont(new java.awt.Font("Sitka Text", 0, 36)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Asistentes:");
        jPanel2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));

        jLabel20.setFont(new java.awt.Font("Sitka Text", 0, 18)); // NOI18N
        jLabel20.setText("Plantel origen:");
        jPanel2.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 120, -1, -1));

        jLabel21.setFont(new java.awt.Font("Sitka Text", 0, 18)); // NOI18N
        jLabel21.setText("Correo del responsable:");
        jPanel2.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, -1, -1));

        jLabel22.setFont(new java.awt.Font("Sitka Text", 0, 18)); // NOI18N
        jLabel22.setText("Fecha del prestamo:");
        jPanel2.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 330, -1, -1));

        jLabel11.setFont(new java.awt.Font("Sitka Text", 0, 18)); // NOI18N
        jLabel11.setText("Motivo del viaje:");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 400, -1, -1));

        bntAceptarYGenerarPDF.setFont(new java.awt.Font("Sitka Text", 0, 18)); // NOI18N
        bntAceptarYGenerarPDF.setText("Aceptar");
        bntAceptarYGenerarPDF.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        bntAceptarYGenerarPDF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntAceptarYGenerarPDFActionPerformed(evt);
            }
        });
        jPanel2.add(bntAceptarYGenerarPDF, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 490, 150, 30));

        btnCancelar.setFont(new java.awt.Font("Sitka Text", 0, 18)); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        jPanel2.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 490, 150, 30));
        jPanel2.add(txtCantPersonas, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 210, 30));
        jPanel2.add(txtCorreoResponsable, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 302, 210, 30));
        jPanel2.add(txtPlantelOrigen, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 150, 200, 30));
        jPanel2.add(txtPlantelDestino, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 220, 190, 30));
        jPanel2.add(txtVehiculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 280, 200, 30));
        jPanel2.add(txtFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 360, 200, 30));
        jPanel2.add(txtMotivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 430, 200, 30));
        jPanel2.add(txtAcompaniante1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 210, 30));
        jPanel2.add(txtAcompaniante3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 440, 210, 30));
        jPanel2.add(txtAcompaniante4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 480, 210, 30));

        txtAcompaniante2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAcompaniante2ActionPerformed(evt);
            }
        });
        jPanel2.add(txtAcompaniante2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, 210, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 670, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 550, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bntAceptarYGenerarPDFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntAceptarYGenerarPDFActionPerformed
      try {
        PrestamoMaestrosFCDPDF controller = new PrestamoMaestrosFCDPDF();
        controller.generarPDF(prestamo, "TicketPrestamoMaestros.pdf");
        JOptionPane.showMessageDialog(this, "Se ha generado el archivo 'TicketPrestamoMaestros.pdf'");
        this.dispose(); // Cierra este frame después de generar el PDF
    } catch (FachadaExceptionPDF e) {
        JOptionPane.showMessageDialog(this, "Error al generar el PDF: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }  
      
    }//GEN-LAST:event_bntAceptarYGenerarPDFActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void txtAcompaniante2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAcompaniante2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAcompaniante2ActionPerformed

    /**
     * @param args the command line arguments
     */
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntAceptarYGenerarPDF;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txtAcompaniante1;
    private javax.swing.JTextField txtAcompaniante2;
    private javax.swing.JTextField txtAcompaniante3;
    private javax.swing.JTextField txtAcompaniante4;
    private javax.swing.JTextField txtCantPersonas;
    private javax.swing.JTextField txtCorreoResponsable;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtMotivo;
    private javax.swing.JTextField txtPlantelDestino;
    private javax.swing.JTextField txtPlantelOrigen;
    private javax.swing.JTextField txtVehiculo;
    // End of variables declaration//GEN-END:variables
}
