/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

/**
 *
 * @author diana
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        this.setLocationRelativeTo(this);
        this.setSize(670, 550);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        bttPrestamo = new javax.swing.JButton();
        bttTraslado = new javax.swing.JButton();
        bttDevolucionPrestamo = new javax.swing.JButton();
        bttDevolucionTraslado = new javax.swing.JButton();
        bttAgregarVehiculo = new javax.swing.JButton();
        bttConsultarChoferes = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(65, 164, 205));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Sitka Text", 0, 36)); // NOI18N
        jLabel1.setText("Menu");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, -1, -1));

        bttPrestamo.setFont(new java.awt.Font("Sitka Text", 0, 18)); // NOI18N
        bttPrestamo.setText("Solicitar Prestamo");
        bttPrestamo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttPrestamoActionPerformed(evt);
            }
        });
        jPanel1.add(bttPrestamo, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 340, 210, 50));

        bttTraslado.setFont(new java.awt.Font("Sitka Text", 0, 18)); // NOI18N
        bttTraslado.setText("Solicitar Traslado");
        jPanel1.add(bttTraslado, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, 210, 50));

        bttDevolucionPrestamo.setFont(new java.awt.Font("Sitka Text", 0, 18)); // NOI18N
        bttDevolucionPrestamo.setText("Devolucion Prestamo");
        jPanel1.add(bttDevolucionPrestamo, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 120, -1, 50));

        bttDevolucionTraslado.setFont(new java.awt.Font("Sitka Text", 0, 18)); // NOI18N
        bttDevolucionTraslado.setText("Devolucion Traslado");
        jPanel1.add(bttDevolucionTraslado, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 230, 210, 50));

        bttAgregarVehiculo.setFont(new java.awt.Font("Sitka Text", 0, 18)); // NOI18N
        bttAgregarVehiculo.setText("Agregar Vehiculo");
        jPanel1.add(bttAgregarVehiculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 230, 210, 50));

        bttConsultarChoferes.setFont(new java.awt.Font("Sitka Text", 0, 18)); // NOI18N
        bttConsultarChoferes.setText("Consultar Choferes");
        jPanel1.add(bttConsultarChoferes, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 340, 210, 50));
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 670, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 550, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bttPrestamoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttPrestamoActionPerformed
        // TODO add your handling code here:
       Prestamo prestamo = new Prestamo();

        prestamo.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bttPrestamoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bttAgregarVehiculo;
    private javax.swing.JButton bttConsultarChoferes;
    private javax.swing.JButton bttDevolucionPrestamo;
    private javax.swing.JButton bttDevolucionTraslado;
    private javax.swing.JButton bttPrestamo;
    private javax.swing.JButton bttTraslado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
